### ISSUE TITLE
All code, content and design © Daniel Furze 2015...

### ISSUE THREAD

**Issue by PJL101** [furzeface/furzeface.com#15]
I am currently having this issue with my site and I'd be interested in your opinion on this.

Does the above statement work hand in hand with the MIT license? I want to have my website open sourced and I was going to put almost the exact same thing but MIT seems to imply you can basically do what you want with the assets/copy anyway.

**Comment by furzeface** [comment]
I'm going [MIT](http://danielfurze.mit-license.org) for the code and [Creative Commons Attribution-ShareAlike 4.0 International](http://creativecommons.org/licenses/by-sa/4.0/legalcode) for the content.

I will change the wording on the page to reflect this as well. 

Is this any help for PJL101/iampjl.co.uk#1?

**Comment by furzeface** [comment]
CC for the blog content because I don't mind people republishing it @PJL101.

**Comment by PJL101** [comment]
Cheers, I'm going for similar.
